micronaut:
  application:
    name: keymanagerGrpc
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/keymanager-grpc
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: update

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true

logger:
  levels:
    io.micronaut.transaction: DEBUG
